#!/usr/bin/env bash
npm run build
rsync -ravzP --delete /Users/thomasbarrett/coding/portfolio/dist/ -e 'ssh -i /Users/thomasbarrett/coding/aws/ireland-key-pair.pem' ubuntu@52.17.9.164:/home/ubuntu/portfolio
